### ISSUE TITLE
CircleCI environment construction

### ISSUE THREAD

**Issue by Akiyoshi999** [Akiyoshi999/divingApp-frontend#1]
# Overview
Build the CircleCI settings in the front-end environment.

## TODO

- [x] Create config.yml and be sure to describe the contents that pass the test.
- [x] Create an issue on github.
- [x] Create a simple test to pass in the local environment.
- [x] Edit config.yml and pass the test in CircleCI environment.
